/*
 * Copyright (C) 2012 Texas Instruments
 *
 *  This program is free software; you can redistribute  it and/or modify it
 *  under  the terms of  the GNU General  Public License as published by the
 *  Free Software Foundation;  either version 2 of the  License, or (at your
 *  option) any later version.
 *
 *  THIS  SOFTWARE  IS PROVIDED   ``AS  IS'' AND   ANY  EXPRESS OR IMPLIED
 *  WARRANTIES,   INCLUDING, BUT NOT  LIMITED  TO, THE IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN
 *  NO  EVENT  SHALL   THE AUTHOR  BE    LIABLE FOR ANY   DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 *  NOT LIMITED   TO, PROCUREMENT OF  SUBSTITUTE GOODS  OR SERVICES; LOSS OF
 *  USE, DATA,  OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 *  ANY THEORY OF LIABILITY, WHETHER IN  CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 *  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *  You should have received a copy of the  GNU General Public License along
 *  with this program; if not, write  to the Free Software Foundation, Inc.,
 *  675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */
#ifndef __ASM_ARCH_HARDWARE_K2HK_H
#define __ASM_ARCH_HARDWARE_K2HK_H

#define K2HK_ASYNC_EMIF_DATA_CE0_BASE	(0x30000000)
#define K2HK_ASYNC_EMIF_DATA_CE1_BASE	(0x34000000)
#define K2HK_ASYNC_EMIF_DATA_CE2_BASE	(0x38000000)
#define K2HK_ASYNC_EMIF_DATA_CE3_BASE	(0x3c000000)

#define K2HK_PLL_CNTRL_BASE		(0x02310000)
#define CLOCK_BASE			K2HK_PLL_CNTRL_BASE

/* PA SS Registers */
#define KS2_PASS_BASE			(0x02000000)

/* PLL control registers */
#define K2HK_MAINPLLCTL0		(KS2_DEVICE_STATE_CTRL_BASE+0x350)
#define K2HK_MAINPLLCTL1		(KS2_DEVICE_STATE_CTRL_BASE+0x354)
#define K2HK_PASSPLLCTL0		(KS2_DEVICE_STATE_CTRL_BASE+0x358)
#define K2HK_PASSPLLCTL1		(KS2_DEVICE_STATE_CTRL_BASE+0x35C)
#define K2HK_DDR3APLLCTL0		(KS2_DEVICE_STATE_CTRL_BASE+0x360)
#define K2HK_DDR3APLLCTL1		(KS2_DEVICE_STATE_CTRL_BASE+0x364)
#define K2HK_DDR3BPLLCTL0		(KS2_DEVICE_STATE_CTRL_BASE+0x368)
#define K2HK_DDR3BPLLCTL1		(KS2_DEVICE_STATE_CTRL_BASE+0x36C)
#define K2HK_ARMPLLCTL0		(KS2_DEVICE_STATE_CTRL_BASE+0x370)
#define K2HK_ARMPLLCTL1		(KS2_DEVICE_STATE_CTRL_BASE+0x374)

/******************************************************************************/
/* Power and Sleep Controller (PSC) Domains */
#define K2HK_LPSC_MOD		0
#define K2HK_LPSC_DUMMY1		1
#define K2HK_LPSC_USB		2
#define KS2_LPSC_USB		K2HK_LPSC_USB
#define K2HK_LPSC_EMIF25_SPI		3
#define K2HK_LPSC_TSIP		4
#define K2HK_LPSC_DEBUGSS_TRC		5
#define K2HK_LPSC_TETB_TRC		6
#define K2HK_LPSC_PKTPROC		7
#define KS2_LPSC_PA			K2HK_LPSC_PKTPROC
#define K2HK_LPSC_SGMII		8
#define KS2_LPSC_CPGMAC		K2HK_LPSC_SGMII
#define K2HK_LPSC_CRYPTO		9
#define KS2_LPSC_CRYPTO		K2HK_LPSC_CRYPTO
#define K2HK_LPSC_PCIE		10
#define K2HK_LPSC_SRIO		11
#define K2HK_LPSC_VUSR0		12
#define K2HK_LPSC_CHIP_SRSS		13
#define K2HK_LPSC_MSMC		14
#define K2HK_LPSC_GEM_0		KS2_LPSC_GEM_0
#define K2HK_LPSC_GEM_1		16
#define K2HK_LPSC_GEM_2		17
#define K2HK_LPSC_GEM_3		18
#define K2HK_LPSC_GEM_4		19
#define K2HK_LPSC_GEM_5		20
#define K2HK_LPSC_GEM_6		21
#define K2HK_LPSC_GEM_7		22
#define K2HK_LPSC_EMIF4F_DDR3A	23
#define K2HK_LPSC_EMIF4F_DDR3B	24
#define K2HK_LPSC_TAC		25
#define K2HK_LPSC_RAC		26
#define K2HK_LPSC_RAC_1		27
#define K2HK_LPSC_FFTC_A		28
#define K2HK_LPSC_FFTC_B		29
#define K2HK_LPSC_FFTC_C		30
#define K2HK_LPSC_FFTC_D		31
#define K2HK_LPSC_FFTC_E		32
#define K2HK_LPSC_FFTC_F		33
#define K2HK_LPSC_AI2		34
#define K2HK_LPSC_TCP3D_0		35
#define K2HK_LPSC_TCP3D_1		36
#define K2HK_LPSC_TCP3D_2		37
#define K2HK_LPSC_TCP3D_3		38
#define K2HK_LPSC_VCP2X4_A		39
#define K2HK_LPSC_CP2X4_B		40
#define K2HK_LPSC_VCP2X4_C		41
#define K2HK_LPSC_VCP2X4_D		42
#define K2HK_LPSC_VCP2X4_E		43
#define K2HK_LPSC_VCP2X4_F		44
#define K2HK_LPSC_VCP2X4_G		45
#define K2HK_LPSC_VCP2X4_H		46
#define K2HK_LPSC_BCP		47
#define K2HK_LPSC_DXB		48
#define K2HK_LPSC_VUSR1		49
#define K2HK_LPSC_XGE		50
#define K2HK_LPSC_ARM_SREFLEX	51
#define K2HK_LPSC_TETRIS		KS2_LPSC_TETRIS

/* DDR3A definitions */
#define K2HK_DDR3A_EMIF_CTRL_BASE		KS2_DDR3_EMIF_CTRL_BASE
#define K2HK_DDR3A_EMIF_DATA_BASE		0x80000000
#define K2HK_DDR3A_DDRPHYC			0x02329000

/* DDR3B definitions */
#define K2HK_DDR3B_EMIF_CTRL_BASE		0x21020000
#define K2HK_DDR3B_EMIF_DATA_BASE		0x60000000
#define K2HK_DDR3B_DDRPHYC			0x02328000

/* Queue manager */
#define DEVICE_QM_MANAGER_BASE          0x02a02000
#define DEVICE_QM_DESC_SETUP_BASE       0x02a03000
#define DEVICE_QM_MANAGER_QUEUES_BASE   0x02a80000
#define DEVICE_QM_MANAGER_Q_PROXY_BASE  0x02ac0000
#define DEVICE_QM_QUEUE_STATUS_BASE	0x02a40000
#define DEVICE_QM_NUM_LINKRAMS          2
#define DEVICE_QM_NUM_MEMREGIONS        20

#define DEVICE_PA_CDMA_GLOBAL_CFG_BASE   0x02004000
#define DEVICE_PA_CDMA_TX_CHAN_CFG_BASE  0x02004400
#define DEVICE_PA_CDMA_RX_CHAN_CFG_BASE  0x02004800
#define DEVICE_PA_CDMA_RX_FLOW_CFG_BASE  0x02005000

#define DEVICE_PA_CDMA_RX_NUM_CHANNELS   24
#define DEVICE_PA_CDMA_RX_NUM_FLOWS      32
#define DEVICE_PA_CDMA_TX_NUM_CHANNELS   9

/* Chip Interrupt Controller */
#define DDR3_ECC_CIC2_IRQ_NUM		0x0D3   /* DDR3 ECC system irq # */
#define DDR3_ECC_CIC2_CHAN_NUM		0x01D   /* DDR3 ECC int mapped to CIC2
						   channel 29 */
/* SGMII SerDes */
#define KS2_SGMII_SERDES2_BASE		-1	/* Not defined */
#define KS2_LANES_PER_SGMII_SERDES	4

/* Number of DSP cores in the SoC */
#define KS2_NUM_DSPS			8

#endif /* __ASM_ARCH_HARDWARE_H */
